
DB2 CREATE DATABASE DBADMIN AUTOMATIC STORAGE NO  ON 'D:\' USING CODESET UTF-8 TERRITORY Lat COLLATE USING SYSTEM PAGESIZE 4096;

DB2ADMIN CREATE

DB2 CREATE TOOLS CATALOG SQMCAT USE EXISTING DATABASE DBADMIN

DB2ADMIN SETID ${usuario} ${password}

db2 update admin cfg using SMTP_SERVER ${ip_servidor_correo}

db2admin stop

db2admin start