
-- Tamaño de los tablespace de una base de datos
SELECT USED_PAGES * 100.0 /TOTAL_PAGES AS SPACE_USED, SUBSTR(TABLESPACE_NAME,1,30) AS TBSPC_NAME FROM TABLE (SNAPSHOT_TBS_CFG ('${base_de_datos}', -1) ) AS SNAPSHOT_TBS_CFG WHERE TOTAL_PAGES != 0 ORDER BY 1 DESC;


-- Tamaño total de una base de datos
SELECT SUM(PAGE_SIZE * TOTAL_PAGES * 1.00)/(1024*1024*1024) FROM TABLE (SNAPSHOT_TBS_CFG('',-1)) WHERE TOTAL_PAGES != 0
